name: Update Google Sheet HTML

on:
  schedule:
    - cron: "*/5 * * * *"   # каждые 30 минут
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Google Sheet ZIP
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/1FcEVDrkvj4DBugXA4Cz5a5mApTsZ4ZEc/export?format=zip&id=1FcEVDrkvj4DBugXA4Cz5a5mApTsZ4ZEc" -o sheet.zip

      - name: Unzip and move files
        run: |
          unzip -o sheet.zip -d tmp
          mkdir -p resources
          mv tmp/Расписание\ групп.html sheet.html
          mv tmp/resources/* resources/
          rm -rf tmp sheet.zip

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add sheet.html resources/*
          git diff --cached --quiet || git commit -m "Update sheet"
          git push
